import * as THREE from 'https://esm.sh/three@0.179.1';
import { OrbitControls } from 'https://esm.sh/three@0.179.1/examples/jsm/controls/OrbitControls.js';

const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const state={events:[],filtered:[],featuredIndex:0,selected:null,section:null,api:null,scene:null,camera:null,renderer:null,controls:null,seatMarker:null,resize:null,theme:localStorage.getItem('neul-theme')||'dark'};
document.documentElement.dataset.theme=state.theme;

function fmtDate(v){if(!v)return'—';return new Intl.DateTimeFormat('zh-TW',{timeZone:'Asia/Taipei',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}
function money(n){return n?`NT$ ${Number(n).toLocaleString('zh-TW')}`:'票價待官方資料'}
function esc(s=''){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function eventStatus(e){const now=Date.now(),start=+new Date(e.dateStart),end=+new Date(e.dateEnd||e.dateStart);if(end<now)return'已結束';if(start<=now&&end>=now)return'進行中';return'即將到來'}
function firstPrice(e){return (e.prices||[])[0]||null}

async function load(){
  try{const r=await fetch('/api/events',{headers:{accept:'application/json'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);state.api=await r.json();state.events=state.api.events||[];}
  catch(e){console.warn('API fallback',e);const r=await fetch('/data/events.seed.json');state.events=await r.json();state.api={generatedAt:new Date().toISOString(),nextRefreshAt:new Date(Date.now()+21600000).toISOString(),refreshPolicy:'local-seed',sources:[],summary:{events:state.events.length,seatMaps:0,prices:state.events.filter(x=>x.prices?.length).length,sourceErrors:0}};}
  state.filtered=state.events; updateSync(); renderAll(); init3D(); startFeatured();
}
function updateSync(){
  $('#syncState').textContent=state.api?.refreshPolicy==='6h-edge-cache'?'6 小時自動更新':'離線種子資料';
  $('#lastSync').textContent=fmtDate(state.api?.generatedAt); $('#nextSync').textContent=fmtDate(state.api?.nextRefreshAt);
}
function eventCard(e){
 const sm=e.automation?.seatMapCaptured||e.seatMapImage; const pc=(e.prices||[]).length>0;
 return `<article class="card event-card" data-id="${esc(e.id)}"><div class="card-cover"></div><div class="card-body"><div class="tags"><span class="tag">${esc(e.artist)}</span><span class="tag ${sm?'good':'warn'}">${sm?'座位圖已抓':'座位圖待抓'}</span><span class="tag ${pc?'good':'warn'}">${pc?'票價已同步':'票價待同步'}</span></div><div class="event-title">${esc(e.title)}</div><div class="meta">${fmtDate(e.dateStart)} · ${esc(e.venue)}<br>${esc(e.ticketing||'')}</div><div class="price">${firstPrice(e)?`最高 ${money(firstPrice(e))}`:'票價資料持續同步'}</div><div class="card-actions"><button class="btn primary" data-view="${esc(e.id)}">開啟 3D</button><button class="btn" data-info="${esc(e.id)}">資料</button></div></div></article>`;
}
function renderAll(){renderFeatured();renderUpcoming();renderEventSelect();renderSources();bindDynamic()}
function featuredEvents(){const arr=state.filtered.filter(e=>e.featured);return arr.length?arr:state.filtered.slice(0,6)}
function renderFeatured(){const arr=featuredEvents();if(!arr.length){$('#featuredGrid').innerHTML='<div class="meta">沒有符合結果</div>';return}const start=state.featuredIndex%arr.length;const picks=[0,1,2].map(i=>arr[(start+i)%arr.length]).filter(Boolean);$('#featuredGrid').innerHTML=picks.map(eventCard).join('');bindDynamic()}
function renderUpcoming(){const arr=state.filtered.filter(e=>eventStatus(e)!=='已結束').slice(0,5);$('#upcomingGrid').innerHTML=arr.map(eventCard).join('')||'<div class="meta">沒有符合結果</div>';bindDynamic()}
function renderEventSelect(){const prev=state.selected?.id;$('#eventSelect').innerHTML=state.events.map(e=>`<option value="${e.id}">${esc(e.artist)} · ${esc(e.venue)}</option>`).join('');const chosen=state.events.find(e=>e.id===prev)||state.events.find(e=>e.id.includes('bts'))||state.events[0];if(chosen){$('#eventSelect').value=chosen.id;selectEvent(chosen.id)}}
function renderSources(){const sources=state.api?.sources||[];$('#auditSummary').textContent=`${state.api?.summary?.events||state.events.length} 活動 · ${state.api?.summary?.seatMaps||0} 座位圖 · ${state.api?.summary?.prices||0} 有票價`;$('#sourceAudit').innerHTML=sources.map(s=>`<div class="audit-item"><b>${esc(s.name)}</b><small>${esc(s.kind)}<br>${esc(s.url)}</small></div>`).join('')||'<div class="audit-item"><b>正式部署後啟用來源掃描</b><small>本機直接開檔會使用種子資料。</small></div>'}
function bindDynamic(){$$('[data-view]').forEach(b=>b.onclick=()=>{selectEvent(b.dataset.view);document.querySelector('#viewer').scrollIntoView({behavior:'smooth'})});$$('[data-info]').forEach(b=>b.onclick=()=>openInfo(b.dataset.info))}
function filter(q){q=q.trim().toLowerCase();state.filtered=!q?state.events:state.events.filter(e=>`${e.artist} ${e.title} ${e.venue} ${e.city}`.toLowerCase().includes(q));state.featuredIndex=0;renderFeatured();renderUpcoming();document.querySelector('#events').scrollIntoView({behavior:'smooth'})}

function selectEvent(id){const e=state.events.find(x=>x.id===id);if(!e)return;state.selected=e;$('#eventSelect').value=id;$('#eventStatusLabel').textContent=eventStatus(e);const secs=(e.sections||[]);$('#sectionSelect').innerHTML=secs.length?secs.map((s,i)=>`<option value="${i}">${esc(s.name)} · ${money(s.price)}</option>`).join(''):'<option value="0">一般視角</option>';$('#sectionCount').textContent=secs.length?`${secs.length} 區`:'未拆票區';state.section=secs[0]||{name:'一般視角',price:firstPrice(e),level:2,angle:0,distance:42};$('#viewEvent').textContent=`${e.artist} · ${e.venue}`;$('#sceneVersion').textContent=`Scene ${e.sceneVersion||'seed'}`;detectSeatMapChange(e);updateSeatSummary();rebuildScene();}
function detectSeatMapChange(e){if(!e.seatMapHash)return;const key=`neul-seatmap-${e.id}`;const old=localStorage.getItem(key);if(old&&old!==e.seatMapHash){showToast('官方座位圖或票價資料有變更，3D 已依新版本重建。')}localStorage.setItem(key,e.seatMapHash)}
function updateSeatSummary(){const e=state.selected,s=state.section;if(!e||!s)return;const row=+$('#rowRange').value,seat=+$('#seatRange').value;$('#rowVal').textContent=`${row} 排`;$('#seatVal').textContent=`${seat} 號`;$('#seatName').textContent=`${s.name} · ${row}排 ${seat}號`;$('#seatPrice').textContent=money(s.price);$('#seatMeta').textContent=`舞台：${labelStage(e.stageType)} · 模擬距離約 ${Math.round((s.distance||42)+row*.7)} m`;$('#viewSeat').textContent=`${s.name} ${row}排${seat}號`;$('#viewDistance').textContent=`約 ${Math.round((s.distance||42)+row*.7)} m`;const warn=s.obstructed||e.obstructed;$('#seatWarn').innerHTML=warn?`<div class="notice warn">⚠ 此區有官方視線受限／遮蔽提醒。3D 會保留舞台硬體與角度限制，但仍以現場架設為準。</div>`:`<div class="notice good">此區目前沒有抓到官方視線遮蔽警示；仍建議開啟官方座位圖交叉確認。</div>`;updateSeatCamera()}
function labelStage(t){return({'center':'中央舞台','center-extended':'中央＋延伸舞台','end':'端景舞台','end-extended':'端景＋延伸舞台'}[t]||'依官方資訊重建')}

function init3D(){const host=$('#viewerCanvas');if(state.renderer)return;state.scene=new THREE.Scene();state.scene.background=new THREE.Color(0x05070d);state.camera=new THREE.PerspectiveCamera(58,host.clientWidth/host.clientHeight,.1,1000);state.camera.position.set(0,26,68);state.renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});state.renderer.setPixelRatio(Math.min(devicePixelRatio,2));state.renderer.setSize(host.clientWidth,host.clientHeight);state.renderer.shadowMap.enabled=true;host.appendChild(state.renderer.domElement);state.controls=new OrbitControls(state.camera,state.renderer.domElement);state.controls.enableDamping=true;state.controls.target.set(0,8,0);const loop=()=>{requestAnimationFrame(loop);state.controls.update();state.renderer.render(state.scene,state.camera)};loop();state.resize=()=>{const w=host.clientWidth,h=host.clientHeight;state.camera.aspect=w/h;state.camera.updateProjectionMatrix();state.renderer.setSize(w,h)};window.addEventListener('resize',state.resize);rebuildScene()}
function clearScene(){while(state.scene.children.length){const o=state.scene.children[0];state.scene.remove(o);o.geometry?.dispose?.();if(o.material){(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose?.())}}}
function rebuildScene(){if(!state.scene||!state.selected)return;clearScene();const e=state.selected;const ambient=new THREE.HemisphereLight(0x6677aa,0x050508,1.35);state.scene.add(ambient);const key=new THREE.DirectionalLight(0xffffff,1.9);key.position.set(-20,45,20);key.castShadow=true;state.scene.add(key);const floor=new THREE.Mesh(new THREE.PlaneGeometry(180,150),new THREE.MeshStandardMaterial({color:0x0b0d14,roughness:.82,metalness:.1}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;state.scene.add(floor);buildStage(e);buildArena(e);buildCrowd();buildRig();buildSeatMarker();updateSeatCamera()}
function buildStage(e){const group=new THREE.Group();const mat=new THREE.MeshStandardMaterial({color:0x252a36,metalness:.65,roughness:.28});const glow=new THREE.MeshStandardMaterial({color:0x725dff,emissive:0x4d3bd4,emissiveIntensity:1.45,roughness:.25});if((e.stageType||'').startsWith('center')){const s=new THREE.Mesh(new THREE.CylinderGeometry(10,10,1.4,8),mat);s.position.y=.7;group.add(s);const ring=new THREE.Mesh(new THREE.TorusGeometry(15,.35,10,64),glow);ring.rotation.x=Math.PI/2;ring.position.y=1.1;group.add(ring);const runway=new THREE.Mesh(new THREE.BoxGeometry(8,1,30),mat);runway.position.set(0,.5,-19);group.add(runway)}else{const main=new THREE.Mesh(new THREE.BoxGeometry(34,2,16),mat);main.position.set(0,1,-35);group.add(main);if((e.stageType||'').includes('extended')){const r=new THREE.Mesh(new THREE.BoxGeometry(7,1,34),mat);r.position.set(0,.5,-13);group.add(r);const b=new THREE.Mesh(new THREE.CylinderGeometry(8,8,1,32),mat);b.position.set(0,.5,5);group.add(b)}const led=new THREE.Mesh(new THREE.PlaneGeometry(27,12),new THREE.MeshBasicMaterial({color:0x755fff}));led.position.set(0,11,-42.8);group.add(led)}state.scene.add(group)}
function buildArena(e){const centerStage=(e.stageType||'').startsWith('center');const colors=[0x262c3b,0x202636,0x1a2130];for(let tier=0;tier<3;tier++){const radius=36+tier*12, y=4+tier*7;const rows=3;for(let r=0;r<rows;r++){const rr=radius+r*2.5;const geo=new THREE.RingGeometry(rr,rr+1.8,96,1,centerStage?0:Math.PI*.15,centerStage?Math.PI*2:Math.PI*1.7);const mesh=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:colors[tier],roughness:.75,side:THREE.DoubleSide}));mesh.rotation.x=-Math.PI/2;mesh.position.y=y+r*1.2;mesh.scale.set(1,1,.78);state.scene.add(mesh)}}}
function buildCrowd(){const count=1200;const g=new THREE.BufferGeometry();const pos=new Float32Array(count*3);for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,r=18+Math.random()*52;pos[i*3]=Math.cos(a)*r;pos[i*3+1]=.7+Math.random()*12;pos[i*3+2]=Math.sin(a)*r*.8}g.setAttribute('position',new THREE.BufferAttribute(pos,3));const p=new THREE.Points(g,new THREE.PointsMaterial({color:0xffb9f2,size:.12,transparent:true,opacity:.85}));state.scene.add(p)}
function buildRig(){for(let i=0;i<8;i++){const a=i/8*Math.PI*2;const light=new THREE.SpotLight(i%2?0x7c66ff:0x62dcff,16,95,Math.PI/12,.45,1.8);light.position.set(Math.cos(a)*26,26,Math.sin(a)*24);light.target.position.set(0,0,0);state.scene.add(light,light.target)}}
function buildSeatMarker(){const g=new THREE.SphereGeometry(.7,16,16);const m=new THREE.MeshStandardMaterial({color:0xff6fb2,emissive:0x7f2454,emissiveIntensity:1});state.seatMarker=new THREE.Mesh(g,m);state.scene.add(state.seatMarker)}
function updateSeatCamera(){if(!state.camera||!state.section)return;const s=state.section,row=+$('#rowRange').value||10;const angle=(s.angle||0)*Math.PI/180;const dist=(s.distance||42)+row*.7;const h=4+(s.level||1)*7+row*.18;const x=Math.sin(angle)*dist,z=Math.cos(angle)*dist;state.seatMarker?.position.set(x,h,z);const zooms=[58,48,39,30,22];const fov=zooms[+$('#zoomRange').value||0];state.camera.fov=fov;state.camera.updateProjectionMatrix();state.camera.position.set(x,h+1.6,z);state.controls?.target.set(0,(state.selected.stageType||'').startsWith('center')?3:7,(state.selected.stageType||'').startsWith('center')?0:-32);state.controls?.update();$('#zoomVal').textContent=['1.0×','1.5×','2×','3×','5×'][+$('#zoomRange').value||0]}
function openInfo(id){const e=state.events.find(x=>x.id===id);if(!e)return;$('#modalTitle').textContent=e.title;$('#modalSub').textContent=`${e.venue} · ${e.ticketing||''}`;const checks=e.sourceChecks||[];$('#modalContent').innerHTML=`<div class="notice ${e.automation?.seatMapCaptured?'good':'warn'}">${e.automation?.seatMapCaptured?'已抓到官方活動頁中的座位／票區圖候選，會產生 Scene Hash。':'目前未抓到可辨識的座位圖；不會假裝有官方座位圖，3D 先用場館與已知舞台配置。'}</div><div class="seatmap empty">${e.seatMapImage?`<img class="seatmap" src="${esc(e.seatMapImage)}" alt="官方座位圖">`:'尚無可直接顯示的官方座位圖'}</div><div class="source-links"><b>來源</b><a href="${esc(e.sourceUrl)}" target="_blank" rel="noopener">${esc(e.sourceUrl)}</a>${e.secondarySourceUrl?`<a href="${esc(e.secondarySourceUrl)}" target="_blank" rel="noopener">${esc(e.secondarySourceUrl)}</a>`:''}</div>${checks.length?`<div class="debug">${esc(JSON.stringify(checks,null,2))}</div>`:''}`;$('#modal').classList.add('open')}
function showToast(msg){const t=document.createElement('div');t.className='overlay-pill';t.style.cssText='position:fixed;right:18px;bottom:18px;z-index:120;background:#151827;padding:13px 16px;max-width:360px;box-shadow:0 18px 60px rgba(0,0,0,.35)';t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),4600)}
function startFeatured(){setInterval(()=>{const arr=featuredEvents();if(arr.length>1){state.featuredIndex=(state.featuredIndex+1)%arr.length;renderFeatured()}},10000)}

$('#themeBtn').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=state.theme;localStorage.setItem('neul-theme',state.theme)};
$('#settingsBtn').onclick=()=>showToast('設定：黑／白模式已可切換；語言與提醒功能保留為獨立模組。');
$('#searchBtn').onclick=()=>filter($('#heroSearch').value);$('#heroSearch').addEventListener('keydown',e=>{if(e.key==='Enter')filter(e.target.value)});$$('[data-q]').forEach(b=>b.onclick=()=>{ $('#heroSearch').value=b.dataset.q;filter(b.dataset.q)});
$('#prevFeatured').onclick=()=>{const n=featuredEvents().length||1;state.featuredIndex=(state.featuredIndex-1+n)%n;renderFeatured()};$('#nextFeatured').onclick=()=>{const n=featuredEvents().length||1;state.featuredIndex=(state.featuredIndex+1)%n;renderFeatured()};
$('#moreBtn').onclick=()=>{$('#modalTitle').textContent='Upcoming 全部活動';$('#modalSub').textContent='可直接選擇活動開啟 3D';$('#modalContent').innerHTML=`<div class="grid">${state.events.filter(e=>eventStatus(e)!=='已結束').map(eventCard).join('')}</div>`;$('#modal').classList.add('open');bindDynamic()};
$('#eventSelect').onchange=e=>selectEvent(e.target.value);$('#sectionSelect').onchange=e=>{const secs=state.selected?.sections||[];state.section=secs[+e.target.value]||state.section;updateSeatSummary()};['#rowRange','#seatRange','#zoomRange'].forEach(s=>$(s).oninput=updateSeatSummary);$('#resetCameraBtn').onclick=updateSeatCamera;$('#seatMapBtn').onclick=()=>openInfo(state.selected?.id);
$('#modalClose').onclick=()=>$('#modal').classList.remove('open');$('#modal').addEventListener('click',e=>{if(e.target===$('#modal'))$('#modal').classList.remove('open')});
load();
