const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const FALLBACK=[
{id:'izna-2026-taipei',artist:'izna',title:'2026 izna Concert Tour: WHO DAT GIRL? in TAIPEI',date:'2026-10-09',time:'18:00',venue:'Zepp New Taipei',city:'新北',status:'upcoming',ticketUrl:'https://tixcraft.com/activity/detail/26_izna',prices:[4280,3880,3580,2140],source:'Tixcraft',seatMapMode:'standing+2f',featured:true},
{id:'ive-2026-dome-demo',artist:'IVE',title:'IVE WORLD TOUR · Taipei Dome Demo',date:'2026-09-12',venue:'臺北大巨蛋',city:'台北',status:'archive',prices:[],source:'NEUL calibration',seatMapMode:'end-stage'}];
let events=[],filter='upcoming',active=null,featureIndex=0,scene,camera,renderer,root,raf;
function today(){return new Date().toISOString().slice(0,10)}
function normalize(list){return list.map(e=>({...e,status:(e.endDate||e.date)<today()?'archive':'upcoming'}))}
async function load(){try{const r=await fetch('/api/events');if(!r.ok)throw 0;events=normalize((await r.json()).events||[])}catch{try{events=normalize(await (await fetch('data/events.json')).json())}catch{events=normalize(FALLBACK)}}renderAll();init3D();}
function renderAll(){renderList();renderArchive();renderFeatured();renderUpcoming();}
function filtered(){return events.filter(e=>e.status===filter)}
function renderList(q=''){let rows=filtered();if(q){q=q.toLowerCase();rows=rows.filter(e=>JSON.stringify(e).toLowerCase().includes(q))} $('#eventList').innerHTML=rows.map(e=>`<div class="eventItem ${active?.id===e.id?'active':''}" data-id="${e.id}"><b>${e.artist}</b><span>${e.title}</span><div class="meta">${e.date}${e.endDate?' – '+e.endDate:''} · ${e.venue}</div></div>`).join('')||'<div class="meta">目前沒有符合資料</div>'; $$('.eventItem').forEach(x=>x.onclick=()=>selectEvent(x.dataset.id));if(!active&&rows[0])selectEvent(rows[0].id)}
function selectEvent(id){active=events.find(e=>e.id===id)||active;renderList($('#searchInput').value.trim());renderInfo();if(scene)buildScene(active)}
function renderInfo(){if(!active)return;const prices=(active.prices||[]).map(p=>`<span class="price">NT$ ${p.toLocaleString()}</span>`).join('')||'<span class="meta">尚未取得票價</span>';$('#info').innerHTML=`<span class="badge">${active.status==='archive'?'Archive':'Upcoming'}</span><h3>${active.artist}</h3><div class="stat"><span>活動</span><b>${active.title}</b></div><div class="stat"><span>日期</span><b>${active.date}${active.endDate?' – '+active.endDate:''} ${active.time||''}</b></div><div class="stat"><span>場館</span><b>${active.venue}</b></div><div class="stat"><span>票價</span><div class="priceGrid">${prices}</div></div><div class="stat"><span>來源</span>${active.ticketUrl?`<a class="source" target="_blank" rel="noopener" href="${active.ticketUrl}">${active.source||'官方來源'} ↗</a>`:`<b>${active.source||'—'}</b>`}</div><div class="quality">3D 自動化流程：活動 → 座位／票價資料 → Section Mapping → 幾何草模 → QA。若座位圖可信度不足，不會硬猜精準排號，而是退回場館基礎模型。</div>`}
function renderArchive(){const a=events.filter(e=>e.status==='archive');$('#archiveGrid').innerHTML=a.map(e=>`<article><b>${e.artist}</b><div>${e.title}</div><div class="meta">${e.date} · ${e.venue}</div></article>`).join('')||'<span class="meta">尚無已結束活動</span>'}
function featuredRows(){return events.filter(e=>e.status==='upcoming'&&e.featured)}
function renderFeatured(){const f=featuredRows();if(!f.length){$('#featuredCard').innerHTML='<div class="meta">目前沒有 Featured 活動</div>';return}const e=f[featureIndex%f.length];$('#featuredCard').innerHTML=`<span class="badge">${e.date}</span><h2>${e.artist}</h2><b>${e.title}</b><div class="meta">${e.venue}${e.prices?.length?' · NT$ '+Math.min(...e.prices).toLocaleString()+' 起':''}</div><button class="primary" style="margin-top:16px;align-self:flex-start" data-feature="${e.id}">查看 3D</button>`;$('[data-feature]')?.addEventListener('click',()=>{filter='upcoming';setFilterButtons();selectEvent(e.id);$('#viewer').scrollIntoView({behavior:'smooth'})})}
function renderUpcoming(){let rows=events.filter(e=>e.status==='upcoming');const d=$('#dateFilter')?.value;if(d)rows=rows.filter(e=>e.date===d||(e.endDate&&d>=e.date&&d<=e.endDate));$('#upcomingGrid').innerHTML=rows.map(e=>`<div class="eventItem" data-modal-id="${e.id}"><b>${e.artist}</b><div>${e.title}</div><div class="meta">${e.date} · ${e.venue}</div></div>`).join('')||'<span class="meta">此日期沒有活動</span>';$$('[data-modal-id]').forEach(x=>x.onclick=()=>{moreDialog.close();filter='upcoming';setFilterButtons();selectEvent(x.dataset.modalId);$('#viewer').scrollIntoView({behavior:'smooth'})})}
function setFilterButtons(){$$('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===filter))}
function init3D(){const el=$('#viewer');scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(48,el.clientWidth/el.clientHeight,.1,1000);renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(el.clientWidth,el.clientHeight);renderer.shadowMap.enabled=true;el.appendChild(renderer.domElement);root=new THREE.Group();scene.add(root);scene.add(new THREE.HemisphereLight(0xffffff,0x35384b,2.1));const d=new THREE.DirectionalLight(0xffffff,2.2);d.position.set(8,14,8);d.castShadow=true;scene.add(d);camera.position.set(0,10,23);camera.lookAt(0,2,0);buildScene(active||filtered()[0]);let drag=false,px=0,py=0;renderer.domElement.onpointerdown=e=>{drag=true;px=e.clientX;py=e.clientY;renderer.domElement.setPointerCapture(e.pointerId)};renderer.domElement.onpointermove=e=>{if(!drag)return;root.rotation.y+=(e.clientX-px)*.008;root.rotation.x=Math.max(-.2,Math.min(.3,root.rotation.x+(e.clientY-py)*.004));px=e.clientX;py=e.clientY};renderer.domElement.onpointerup=()=>drag=false;renderer.domElement.onwheel=e=>{camera.position.z=Math.max(12,Math.min(34,camera.position.z+e.deltaY*.012))};addEventListener('resize',()=>{camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();renderer.setSize(el.clientWidth,el.clientHeight)});(function tick(){raf=requestAnimationFrame(tick);renderer.render(scene,camera)})()}
function clearGroup(){while(root.children.length){const c=root.children.pop();c.geometry?.dispose();if(c.material){Array.isArray(c.material)?c.material.forEach(m=>m.dispose()):c.material.dispose()}}}
function mat(color,rough=.72){return new THREE.MeshStandardMaterial({color,roughness:rough,metalness:.08})}
function box(w,h,d,color){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(color));m.castShadow=m.receiveShadow=true;return m}
function buildScene(e){if(!root)return;clearGroup();const floor=box(20,.35,18,document.documentElement.classList.contains('light')?0xeef0f5:0xd8dbe4);floor.position.y=-.2;root.add(floor);const stage=box(9,.8,4,0x252838);stage.position.set(0,.4,-5.6);root.add(stage);const screen=box(7.6,4.6,.35,0x3a3f62);screen.position.set(0,3,-7.15);root.add(screen);const glow=new THREE.PointLight(0x765fff,34,22);glow.position.set(0,5,-4);root.add(glow);const mode=e?.seatMapMode||'end-stage';const rows=mode==='standing+2f'?8:14;for(let r=0;r<rows;r++){const z=-1+r*.82;const width=mode==='standing+2f'?(r<4?14:17):(12+r*.35);const count=Math.max(12,Math.round(width/.62));for(let i=0;i<count;i++){const x=-width/2+i*(width/(count-1));if(Math.abs(x)<1.3&&r%4===0)continue;const seat=box(.38,.32,.38,0x6f75a6);seat.position.set(x,.23+r*.075,z);seat.rotation.y=(x/width)*-.12;root.add(seat)}}if(mode!=='standing+2f'){for(let side of [-1,1])for(let r=0;r<7;r++){const rail=box(3.8,.28,7.5,0x8086a8);rail.position.set(side*(8+r*.16),1.2+r*.58,1.8);rail.rotation.z=side*.04;root.add(rail)}}else{const pit=box(12,.12,6,0xadb0ba);pit.position.set(0,.04,-.8);root.add(pit)}root.rotation.set(-.05,0,0);camera.position.set(0,10,23);camera.lookAt(0,2,-1)}
$('#themeBtn').onclick=()=>{document.documentElement.classList.toggle('light');buildScene(active)};$$('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;active=null;setFilterButtons();renderList()});$('#searchBtn').onclick=()=>renderList($('#searchInput').value.trim());$('#searchInput').addEventListener('keydown',e=>{if(e.key==='Enter')renderList(e.target.value.trim())});$('#moreBtn').onclick=()=>{renderUpcoming();moreDialog.showModal()};$('#closeModal').onclick=()=>moreDialog.close();$('#dateFilter').onchange=renderUpcoming;$('#clearDate').onclick=()=>{$('#dateFilter').value='';renderUpcoming()};$('#settingsBtn').onclick=()=>alert('設定：深淺色切換已獨立保留；語言與提醒可在下一輪接回自動資料層。');$('#menuBtn').onclick=()=>alert('手機導覽：首頁 / 演唱會 / 3D 場館 / 我的清單 / 提醒');$('#viewStage').onclick=()=>{camera.position.set(0,6,14);camera.lookAt(0,2,-5)};$('#viewSeat').onclick=()=>{camera.position.set(6,4,8);camera.lookAt(0,2,-4)};$('#resetView').onclick=()=>{root.rotation.set(-.05,0,0);camera.position.set(0,10,23);camera.lookAt(0,2,-1)};setInterval(()=>{if(featuredRows().length>1){featureIndex++;renderFeatured()}},10000);load();
