import fs from 'node:fs';
const read=p=>fs.readFileSync(new URL(`../${p}`,import.meta.url),'utf8');
let ok=true;const fail=m=>{console.error(m);ok=false;};
const app=read('app.js'),events=read('api/events.js'),official=read('api/official.js'),refresh=read('api/refresh.js'),coverage=read('api/coverage.js'),seat=read('api/seat-map-image.js'),news=read('api/entertainment-news.js'),intel=read('seat-map-intelligence.js'),sw=read('sw.js');
if(!/SERVER_REFRESH_MS = 6 \* 60 \* 60 \* 1000/.test(app)) fail('6h client refresh constant missing');
if(!/s-maxage=21600/.test(events)||!/21600000/.test(events)) fail('events 6h cache/next-update missing');
if(!/s-maxage=21600/.test(official)||!/Date\.now\(\)\/21600000/.test(official)) fail('official 6h cache/rotation missing');
if(/Date\.now\(\).*warm=|warm=\$\{Date\.now/.test(refresh)||/coverage=\$\{Date\.now/.test(coverage)) fail('timestamp cache busting still present');
if(!/s-maxage=21600/.test(seat)||!/status===404[^\n]*s-maxage=21600/.test(seat)) fail('seat-map success/miss cache protection missing');
if(!/SEATMAP_BACKGROUND_MAX = 1/.test(app)||!/interactive\?3:1/.test(app)||!/sourceSignature/.test(app)) fail('lazy seat-map hydration guard missing');
if(!/maxSources/.test(intel)||!/slice\(0,maxSources\)/.test(intel)) fail('seat-map source fanout limit missing');
if(!/s-maxage=3600/.test(news)) fail('news RSS 1h cache missing');
if(!/neul-v0\.40\.14-cpu-saver/.test(sw)) fail('service worker version not bumped');
if(!ok)process.exit(1);
console.log('NEUL v0.40.14 CPU Saver checks passed · 6h shared API cache · no timestamp busting · lazy seat-map hydration · cached misses');
