import fs from 'node:fs';
import { parseTwConcertViewCalendar } from '../lib/twconcertview-discovery.js';
let ok=true; const fail=(m,x='')=>{console.error('FAIL',m,x);ok=false;};
const pkg=JSON.parse(fs.readFileSync(new URL('../package.json',import.meta.url),'utf8'));
if(pkg.version!=='0.40.13') fail('package must be 0.40.13',pkg.version);
const apiNews=fs.readFileSync(new URL('../api/entertainment-news.js',import.meta.url),'utf8');
if(!apiNews.includes('when:7d')) fail('news freshness window is not 7 days');
if(!apiNews.includes('.sort((a,b) => Date.parse(b.publishedAt) - Date.parse(a.publishedAt))')) fail('news is not sorted newest-first');
if(!apiNews.includes('.slice(0, 32)')) fail('news API does not retain enough fresh items for view-more');
const clientNews=fs.readFileSync(new URL('../news.js',import.meta.url),'utf8');
if(!clientNews.includes('visible: 8')) fail('news initial visible count must be 8');
if(!clientNews.includes('state.visible+=8')) fail('news view-more paging missing');
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
if(!html.includes('id="newsMoreBtn"')) fail('news view-more button missing');
if(!html.includes('最近 7 天')) fail('news freshness copy missing');
const app=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');
if(app.includes('實拍視角 ↗')) fail('third-party sightline calibration link is still exposed in UI');
if(!app.includes("referrerPolicy='no-referrer'")) fail('official-map direct-image no-referrer fallback missing');
if(!app.includes('ARCHIVE_LIMIT = 20')) fail('archive hard limit 20 missing');
const twcv=fs.readFileSync(new URL('../lib/twconcertview-discovery.js',import.meta.url),'utf8');
if(!twcv.includes('extractCalendarPageLinks')) fail('dynamic calendar-link discovery missing');
if(!twcv.includes('futureReferenceEvents')) fail('old cross-check items are not pruned');
const fixture=`<title>近期 316 場演出</title><a href="/en/calendar?month=10&year=2026">Oct</a><div>2026-09-25｜SKE48｜Clapper Studio</div><div>2026-09-25｜SKE48｜Clapper Studio</div><div>2026-09-26｜TREASURE｜高雄巨蛋</div>`;
const parsed=parseTwConcertViewCalendar(fixture,{sourceUrl:'https://twconcertview.com/en/calendar'});
if(parsed.referenceCount!==316) fail('316 coverage reference not parsed',parsed.referenceCount);
if(parsed.events.length!==2) fail('same-day duplicate coverage items not deduped',parsed.events.length);
if(!ok) process.exit(1);
console.log('NEUL v0.40.13 checks passed · 316 candidate reconciliation · recent-only Archive20 · 7-day newest-first news · news view-more · hidden sightline calibration source · official-map direct fallback');
